@Play.Catalog.Service_HostAddress = http://localhost:5076

GET {{Play.Catalog.Service_HostAddress}}/api/Items
Accept: application/json

###
POST {{Play.Catalog.Service_HostAddress}}/api/Items
Content-Type: application/json

{
    "name": "NewItem",
    "description": "New item description",
    "price": 9.99
}

###
PUT {{Play.Catalog.Service_HostAddress}}/api/Items/1
Content-Type: application/json

{
    "name": "UpdatedItem",
    "description": "Updated item description",
    "price": 19.99
}

###
DELETE {{Play.Catalog.Service_HostAddress}}/api/Items/1